### ISSUE TITLE
No Such Export

### ISSUE THREAD

**Issue by Sojobo** [jaimeadf/discord-screenshot#10]
![image](https://user-images.githubusercontent.com/629811/102018227-f1a34d80-3d63-11eb-970c-5cad629b6a53.png)
I have been getting the following error after the most recent update. The resource is running and I can use the screenshot -1 command to trigger screenshots from all players so I'm not sure why the export has stopped working.

**Comment by Sojobo** [comment]
Just noticed the addition of a callback, I've adjust my code, this was likely the issue but I'll re-open if not.

**Comment by jaimeadf** [comment]
The callback is an optional parameter so I don't think that's the problem. I'll be taking a better look tomorrow.

**Comment by jaimeadf** [comment]
Fixed, thanks for reporting.

**Comment by Sojobo** [comment]
Thanks dude ❤
