### ISSUE TITLE
(node:9956) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by TechnoBehemoth** [jaimeadf/discord-screenshot#12]
Seeing this error twice in the server console. I'm on artifact 2873, which is newer than the suggested version. I'm seeing Buffer being used in both discord-screenshot as well as screen-shot basic. Is there a resolution for this error?

**Comment by jaimeadf** [comment]
The warning is originated by the koa-body package that is used in screenshot-basic. It’s not related to discord-screenshot nor FiveM. The package just needs to be updated in screenshot-basic and the warning will vanish.

**Comment by TechnoBehemoth** [comment]
> The warning is originated by the koa-body package that is used in screenshot-basic. It’s not related to discord-screenshot nor FiveM. The package just needs to be updated in screenshot-basic and the warning will vanish.

Thank you for confirming. Is it safe to say I can ignore that error in the server console for the time being?

Thanks

**Comment by jaimeadf** [comment]
Yes, it won't affect anything. I would have made a pull request to screenshot-basic, but seems like it is abandoned. So I will be making the changes myself and releasing it.

**Comment by TechnoBehemoth** [comment]
> Yes, it won't affect anything. I would have made a pull request to screenshot-basic, but seems like it is abandoned. So I will be making the changes myself and releasing it.

Awesome, thanks for your help and quick responses!

**Comment by iliasroleplay** [comment]
Hey jaimeadf did you perchance find a solution to the error? I would appreciate it if you share it with us!
