### ISSUE TITLE
Deprecated code

### ISSUE THREAD

**Issue by Sojobo** [jaimeadf/discord-screenshot#14]
As far as I know this doesn't cause any issues, just a warning about a deprecated function being used;

`(node:8628) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

(node:8628) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

I get this same warning twice when triggering screenshots.

**Comment by jaimeadf** [comment]
It's caused by an outdated package in screenshot-basic, not being related to discord-screenshot.
