### ISSUE TITLE
No such export requestClientScreenshot in resource screenshot-basic

### ISSUE THREAD

**Issue by roobr** [jaimeadf/discord-screenshot#15]
No such export requestClientScreenshot in resource screenshot-basic

was working fine but recently stopped working and returned

![image](https://user-images.githubusercontent.com/9066749/104087209-37dfc400-52b2-11eb-8934-6e14337ebbf3.png)

**Comment by jaimeadf** [comment]
This is probably related to an installation issue. If you want message on discord and I'll help you fix it.

Sorry for the long wait.
