### ISSUE TITLE
[Improvement] Move Webhook Server sided

### ISSUE THREAD

**Issue by PaulyJ1** [jaimeadf/discord-screenshot#17]
As is common practice on the internet, we should never trust a client.

In that respect, it would be more secure moving the webhookUrl out of the settings.json and into server.js

**Comment by jaimeadf** [comment]
You're right, we never should trust the client and share sensitive information with it. But everything is already only server side as you can see with the `server_only` flag in fxmanifest.lua. So nor the settings.json nor the webhook URL is sent to client.
