### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by FlavieMannala** [jaimeadf/discord-screenshot#18]
(node:2052) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by jaimeadf** [comment]
This was already responded [here](https://github.com/jaimeadf/discord-screenshot/issues/12) if you got any more questions let me know.
