### ISSUE TITLE
How can i use ur code to create a comand?

### ISSUE THREAD

**Issue by Emanucas12** [jaimeadf/discord-screenshot#2]
I want to use ur code to create command like that

"RegisterCommand('instagram', function(source, args)
	exports['discord-screenshot']:requestClientScreenshotDiscordUpload(GetPlayers()[1], {
   	name = 'Instagram',
    avatarUrl = 'https://canary.discord.com/assets/f78426a064bc9dd24847519259bc42af.png'
    })
end)" and i want the person who uses the comand its the same who get the screenshot to discord, how can i make that?

**Comment by jaimeadf** [comment]
The first parameter is the player's source. So instead of using `GetPlayers()[1]` just pass the `source` like the example below:

```lua
RegisterCommand('instagram', function(source, args)
    exports['discord-screenshot']:requestClientScreenshotDiscordUpload(source, {
        name = 'Instagram',
        avatarUrl = 'https://canary.discord.com/assets/f78426a064bc9dd24847519259bc42af.png'
    })
end)
```

**Comment by jaimeadf** [comment]
I hope this helps.

**Comment by jaimeadf** [comment]
Don't forget that this code needs to be in the server.
