### ISSUE TITLE
screenshot-basic now uses POST headers.

### ISSUE THREAD

**Issue by VIRUXE** [jaimeadf/discord-screenshot#24]
Both the project-error version of screenshot-basic and CitizenFX are now using headers. Might want to update that. Or even just provide compatibility with project-error's fork of screenshot-basic

I've never done anything in typescript before but might have a go at doing a pull request. Deixa ver como corre...

**Comment by jaimeadf** [comment]
The version that ships with discord-screenshot is just screenshot-basic pre-compiled without any modifications, but I'll update it. Thanks for letting me know.
