### ISSUE TITLE
error

### ISSUE THREAD

**Issue by niodamian** [jaimeadf/discord-screenshot#28]
(node:3908) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `FXServer --trace-deprecation ...` to show where the warning was created)

**Comment by tugapower0** [comment]
Having the same, managed to fix that warning ?

**Comment by jaimeadf** [comment]
#12
