### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by JaredScar** [jaimeadf/discord-screenshot#5]
This isn't really an issue. Moreso a question. I was wondering if there was a way to use your API to have the screenshot displayed inside of the embed instead of outside of it. I know it's possible, but you need to put a placeholder name in the embed that the attached file has as its name. 

I can maybe help you try to add this if needed.

Best Regards,
Badger (on FiveM forums)

**Comment by jaimeadf** [comment]
Feel free to message me in discord and we talk more there.
My discord: `Marmota#0001`

**Comment by JaredScar** [comment]
Added! I am Badger#0002
